/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "2D color picker",
  "description": "Wow Joe 2D",
  "tags": [],
  "credits": [
    {
      "name": "Ucrash"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "enabledByDefault": true
};
export default manifest;
